# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 14, 11, 48, 4, 734284)),
        ),
    ]
