# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180115_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 16, 22, 51, 39, 83975)),
        ),
    ]
